stages:
  - test
  - build

test-back:
  image: gradle:jdk21
  stage: test
  script:
      - export GRADLE_USER_HOME=`pwd`/.gradle
      - echo $CI_COMMIT_BRANCH
      - ./gradlew check test

build-main:
  image: gradle:jdk21
  stage: build
  script:
      - export GRADLE_USER_HOME=`pwd`/.gradle
      - ./gradlew build
  only:
    - main